
runtime:
  seed: 42
  n_jobs: -1
  use_gpu: true

io:
  artifacts_dir: "./artifacts"
  cache_features: true

data:
  date_col_candidates: ["date","ds"]
  target_col_candidates: ["sales","y","target"]
  id_col_candidates: ["store_id","menu_id","series_id","영업장명","메뉴명"]
  min_context_days: 28
  min_positive_ratio: 0.01

features:
  fourier: { weekly_K: 3, yearly_K: 10 }
  lags: [1,2,7,14,28,365]
  rollings: [7,14,28]
  use_holidays: false
  intermittency: { enable: true }

model:
  classifier:
    num_leaves: 63
    learning_rate: 0.05
    n_estimators: 2000
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 1.0
    reg_lambda: 1.0
    device_type: gpu
  regressor:
    objective: "tweedie"
    tweedie_variance_power: 1.2
    num_leaves: 127
    learning_rate: 0.03
    n_estimators: 4000
    subsample: 0.8
    colsample_bytree: 0.8
    min_data_in_leaf: 50
    device_type: gpu
  calibration:
    enable: false
    method: "isotonic"

cv:
  horizon: 7
  init_train_ratio: 0.7
  early_stopping_rounds: 100
  n_folds_min: 2
  time_series_split: "rolling_origin"
  min_positive_samples: 10
  min_negative_samples: 10

threshold:
  grid_start: 0.01
  grid_end: 0.99
  grid_step: 0.01
