
runtime:
  seed: 42
  n_jobs: -1
  use_gpu: true

io:
  artifacts_dir: "./artifacts"
  cache_features: true

data:
  date_col_candidates: ["영업일자"]
  target_col_candidates: ["매출수량"]
  id_col_candidates: ["store_id", "menu_id", "store_menu_id"]
  min_context_days: 7
  min_positive_ratio: 0.01
  use_weights: true

features:
  fourier: { weekly_K: 3, yearly_K: 10 }
  lags: [1,2,7,14,28,365]
  rollings: [7,14,28]
  # Whether to include holiday-based features. Set to false to disable.
  use_holidays: false
  intermittency: { enable: true }
  dtw:
    enable: false   # or false
    n_clusters: 2
    use_gpu: false

model:
  classifier:
    num_leaves: 127  # Reduce if GPU memory is insufficient
    learning_rate: 0.02
    n_estimators: 2000
    subsample: 0.9
    feature_fraction: 0.9
    reg_alpha: 1.0
    reg_lambda: 0.4
    verbose: -1
    device_type: gpu
    gpu_use_dp: false
    max_bin: 255  # Reduce if GPU memory is insufficient
  regressor:
    objective: "tweedie"
    tweedie_variance_power: 1.2
    num_leaves: 127  # Reduce if GPU memory is insufficient
    learning_rate: 0.03
    n_estimators: 4000
    subsample: 0.9
    feature_fraction: 0.9
    min_child_samples: 20
    verbose: -1
    device_type: gpu
    gpu_use_dp: false
    max_bin: 255  # Reduce if GPU memory is insufficient
  calibration:
    enable: false
    method: "isotonic"

cv:
  horizon: 7
  init_train_ratio: 0.7
  early_stopping_rounds: 100
  n_folds_min: 2
  time_series_split: "rolling_origin"
  min_positive_samples: 10
  min_negative_samples: 10

threshold:
  grid_start: 0.01
  grid_end: 0.99
  grid_step: 0.01
